export const EN_TO_PT: Record<string, string> = {
  "Brazil": "Brasil",
  "Argentina": "Argentina",
  "Mexico": "México",
  "United States": "EUA",
  "USA": "EUA",
  "Canada": "Canadá",
  "Spain": "Espanha",
  "Germany": "Alemanha",
  "France": "França",
  "England": "Inglaterra",
  "Italy": "Itália",
  "Portugal": "Portugal",
  "Netherlands": "Países Baixos",
  "Belgium": "Bélgica",
  "Switzerland": "Suíça",
  "Austria": "Áustria",
  "Croatia": "Croácia",
  "Denmark": "Dinamarca",
  "Poland": "Polônia",
  "Serbia": "Sérvia",
  "Norway": "Noruega",
  "Sweden": "Suécia",
  "Czech Republic": "República Tcheca",
  "Turkey": "Turquia",
  "Greece": "Grécia",
  "Russia": "Rússia",
  "Ukraine": "Ucrânia",
  "Scotland": "Escócia",
  "Wales": "País de Gales",
  "Northern Ireland": "Irlanda do Norte",
  "Republic of Ireland": "Irlanda",
  "Hungary": "Hungria",
  "Romania": "Romênia",
  "Morocco": "Marrocos",
  "Senegal": "Senegal",
  "Algeria": "Argélia",
  "Tunisia": "Tunísia",
  "Ghana": "Gana",
  "Nigeria": "Nigéria",
  "Cameroon": "Camarões",
  "Ivory Coast": "Costa do Marfim",
  "Egypt": "Egito",
  "South Africa": "África do Sul",
  "Mali": "Mali",
  "Cape Verde": "Cabo Verde",
  "Japan": "Japão",
  "South Korea": "Coreia do Sul",
  "Korea Republic": "Coreia do Sul",
  "Iran": "Irã",
  "Saudi Arabia": "Arábia Saudita",
  "Qatar": "Qatar",
  "Australia": "Austrália",
  "New Zealand": "Nova Zelândia",
  "Uzbekistan": "Uzbequistão",
  "Jordan": "Jordânia",
  "Iraq": "Iraque",
  "United Arab Emirates": "Emirados Árabes Unidos",
  "UAE": "Emirados Árabes Unidos",
  "Uruguay": "Uruguai",
  "Colombia": "Colômbia",
  "Chile": "Chile",
  "Paraguay": "Paraguai",
  "Peru": "Peru",
  "Ecuador": "Equador",
  "Venezuela": "Venezuela",
  "Bolivia": "Bolívia",
  "Panama": "Panamá",
  "Costa Rica": "Costa Rica",
  "Jamaica": "Jamaica",
  "Honduras": "Honduras",
  "El Salvador": "El Salvador",
  "Guatemala": "Guatemala",
  "Curaçao": "Curaçao",
  "Curacao": "Curaçao",
  "Bosnia & Herzegovina": "Bósnia e Herzegovina",
};

export function resolvePtName(enName: string): string {
  return EN_TO_PT[enName] ?? enName;
}
